#
# Projeto: bashrc-for-devs
#
# Script: ~/.bash_profile
# Descrição: Carrega o ~/.profile e o ~/.bashrc.
# Nota: Executado por login shells interativos.
# ==========================================================================================

# generated by Git for Windows
test -f ~/.profile && source ~/.profile
test -f ~/.bashrc && source ~/.bashrc

#--------------------------------------------------------------------------------
#--- Final do script '~/.bash_profile'
#--------------------------------------------------------------------------------
