#
# =============================================================================
# Script: ~/.bash_profile
# Executado por login shells interativos.
# Carrega o ~/.profile e o ~/.bashrc.
# =============================================================================

# generated by Git for Windows
test -f ~/.profile && source ~/.profile
test -f ~/.bashrc && source ~/.bashrc

#--------------------------------------------------------------------------------
#--- Final do script '~/.bash_profile'
#--------------------------------------------------------------------------------
